### ISSUE TITLE
PythonLoader  fails parsing crawlers from config file.

### ISSUE THREAD

**Issue by asvbarbosa** [kombiHQ/kombi#73]
## summary
After defining crawlers in a config file ( yaml ) , I get an operation error about  operator ">" does not work with lists.
So basically after looking into the PythonLoader.py, I spotted the problem on line number 304 under the definition "__parseInlineCrawlers".

### original:
            for crawlerKey, varExtractorExpression in contents['crawlers'].items():
                parts = crawlerKey.split('<')
                BaseCrawler = Crawler
                if parts > 1:
                    BaseCrawler = Crawler.registeredType(parts[1].strip())

### Fix:
            for crawlerKey, varExtractorExpression in contents['crawlers'].items():
                parts = crawlerKey.split('<')
                BaseCrawler = Crawler
                if len(parts) > 1:
                    BaseCrawler = Crawler.registeredType(parts[1].strip())

**Comment by paulondc** [comment]
Thanks Victor, I've committed a fix for it under the master branch
